name: Example workflow for Node using Snyk
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNUK }}
      - uses: actions/checkout@v3
      # https://github.com/actions/setup-node
      - uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm' # ускоряет повторные сборки
      - run: npm ci
      - run: npm test